# --- !Ups

create table "course" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "title" varchar not null,
  "author" varchar
);

# --- !Downs

drop table "course" if exists;
