# --- !Ups
create table "nodeTypes" (
  "id" int not null primary key,
  "type" varchar not null
);

create table "node" (
  "id" bigint generated by default as identity(start with 10000) not null primary key,
  "name" varchar not null,
  "authors" varchar not null,
  "type" varchar not null,
  "prv" bigint,
  "nxt" bigint,
  "parent" bigint,
  "data" varchar,
  "created_at" timestamp default current_timestamp,
  "modified_at" timestamp default current_timestamp,
  foreign key (type) references nodeTypes (type),
  foreign key (prv) references nodeTypes (id),
  foreign key (nxt) references nodeTypes (id),
  foreign key (parent) references nodeTypes (id)
);

create trigger node_update before update on node
for each row begin
  set new.modified_at = CURRENT_TIMESTAMP;
end;

# --- !Downs
drop trigger if exists node_update;
drop table if exists "node";
drop table if exists "nodeTypes";
